version: '3.8'

services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
      - PORT=4000
      - JWT_SECRET=${JWT_SECRET:-your-super-secret-jwt-key-here}
      - FOOTBALL_DATA_KEY=${FOOTBALL_DATA_KEY}
      - API_FOOTBALL_KEY=${API_FOOTBALL_KEY}
    volumes:
      - ./backend/data:/app/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      - VITE_API_URL=http://localhost:4000
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  data:
