networks:
  sportskalendar-dev:
    driver: bridge

volumes:
  postgres_data_dev:

services:
  postgres:
    image: postgres:15-alpine
    container_name: sportskalendar-db-dev
    environment:
      POSTGRES_DB: sportskalendar
      POSTGRES_USER: sportskalendar
      POSTGRES_PASSWORD: dev_password_change_me
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    networks:
      - sportskalendar-dev
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sportskalendar -d sportskalendar"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: sportskalendar-backend-dev
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=development
      - PORT=4000
      - DATABASE_URL=postgresql://sportskalendar:dev_password_change_me@postgres:5432/sportskalendar
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=sportskalendar
      - DB_USER=sportskalendar
      - DB_PASSWORD=dev_password_change_me
      - JWT_SECRET=dev_secret_change_in_production_minimum_32_characters
      - CORS_ORIGIN=http://localhost:5173,http://localhost:3000
      - FOOTBALL_DATA_KEY=${FOOTBALL_DATA_KEY:-}
      - API_FOOTBALL_KEY=${API_FOOTBALL_KEY:-}
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY:-}
      - STRIPE_WEBHOOK_SECRET=${STRIPE_WEBHOOK_SECRET:-}
      - STRIPE_PRICE_ID=${STRIPE_PRICE_ID:-}
      - FRONTEND_URL=${FRONTEND_URL:-http://localhost:5173}
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./backend/src:/app/src
      - ./backend/data:/app/data
    networks:
      - sportskalendar-dev
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Frontend for development - just for testing the build
  # In development, run "npm run dev" locally for hot reload
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_API_URL: http://localhost:4000/api
    container_name: sportskalendar-frontend-dev
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - sportskalendar-dev
    restart: unless-stopped

