name: Deploy Storybook

on:
  push:
    branches: [ main ]
    paths:
      - 'frontend/src/**'
      - 'frontend/.storybook/**'
      - 'frontend/package.json'
  pull_request:
    branches: [ main ]
    paths:
      - 'frontend/src/**'
      - 'frontend/.storybook/**'
      - 'frontend/package.json'

jobs:
  deploy-storybook:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name == github.repository
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json
    
    - name: Install dependencies
      run: cd frontend && npm ci
    
    - name: Build Storybook
      run: cd frontend && npm run build-storybook
    
    - name: Deploy to GitHub Pages
      if: github.ref == 'refs/heads/main'
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./frontend/storybook-static
        destination_dir: storybook
    
    - name: Deploy to Chromatic (for PRs)
      if: github.event_name == 'pull_request' && secrets.CHROMATIC_PROJECT_TOKEN != ''
      uses: chromaui/action@v1
      with:
        projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
        buildScriptName: build-storybook
        workingDir: frontend
        onlyChanged: true
        skip: ${{ github.event.pull_request.draft }}
