name: Test on Commit

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  quick-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: |
          frontend/package-lock.json
          backend/package-lock.json
    
    - name: Install frontend dependencies
      run: cd frontend && npm ci
    
    - name: Install backend dependencies
      run: cd backend && npm ci
    
    - name: Frontend TypeScript check
      run: cd frontend && npx tsc --noEmit
    
    - name: Backend TypeScript check
      run: cd backend && npx tsc --noEmit
    
    - name: Frontend linting
      run: cd frontend && npm run lint
    
    - name: Run frontend tests (fast)
      run: cd frontend && npm test -- --run --reporter=verbose
    
    - name: Build frontend
      run: cd frontend && npm run build
    
    - name: Build backend
      run: cd backend && npm run build

  integration-tests:
    runs-on: ubuntu-latest
    needs: quick-tests
    if: github.event_name == 'pull_request'
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json
    
    - name: Install dependencies
      run: cd frontend && npm ci
    
    - name: Run full test suite with coverage
      run: cd frontend && npm run test:coverage
    
    - name: Build Storybook
      run: cd frontend && npm run build-storybook
    
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
        files: ./frontend/coverage/lcov.info
        flags: frontend
        name: frontend-coverage
        fail_ci_if_error: false
        verbose: true
